# Generated by Django 5.2.4 on 2025-07-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('correo_cliente', models.EmailField(max_length=254)),
                ('telefono_cliente', models.CharField(max_length=15)),
                ('fecha_reserva', models.DateField()),
                ('hora_reserva', models.TimeField()),
                ('cantidad_personas', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
