# Generated by Django 5.2.4 on 2025-07-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_reserva_mesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='mesa',
            name='ocupada',
            field=models.BooleanField(default=False),
        ),
    ]
