# Generated by Django 5.2.4 on 2025-07-28 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_remove_mesa_capacidad_remove_mesa_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.mesa'),
        ),
    ]
